apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-remove-kubeadmin
  namespace: policies
  labels:
    category: security
    policyset: security-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: remove-kubeadmin-secret
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: kubeadmin
                  namespace: kube-system
